### ISSUE TITLE
plot_gffcmp_stats.py error

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/ont_tutorial_pinfish#6]
I used to succeed with my former conda env but it got compromised.
I just created a fresh conda env to rerun the workflow (which worked until the step of plotting) and I then get the error below.
Any idea what could be wrong and which package I should change (matplot!)?
Thanks in advance
Stephane

[conda_list.txt](https://github.com/nanoporetech/ont_tutorial_pinfish/files/3534063/conda_list.txt)

```
rule plotPinfishStats: ## plot_gffcmp_stats.py script from https://github.com/nanoporetech/wub
    input:
        gff = "Analysis/Pinfish/polished_transcripts_collapsed.gff"
    output:
        pdf = "Analysis/Pinfish/plot_gffcmp_stats.pdf",
        png = "Static/Images/plot_gffcmp_stats.png"
    shell:
        "plot_gffcmp_stats.py -r {output.pdf} {input.gff} && convert {output.pdf}[0] {output.png}"
```

```
plot_gffcmp_stats.py -r Analysis/Pinfish/plot_gffcmp_stats.pdf Analysis/Pinfish/polished_transcripts_collapsed.gff
Traceback (most recent call last):
  File "/opt/biotools/miniconda3/envs/pinfish_3.6/bin/plot_gffcmp_stats.py", line 226, in <module>
    total.plot(ax=plt.gca(), kind='barh', sharex=False, title='Totals')
  File "/opt/biotools/miniconda3/envs/pinfish_3.6/lib/python3.6/site-packages/pandas/plotting/_core.py", line 794, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/opt/biotools/miniconda3/envs/pinfish_3.6/lib/python3.6/site-packages/pandas/plotting/_matplotlib/__init__.py", line 62, in plot
    plot_obj.generate()
  File "/opt/biotools/miniconda3/envs/pinfish_3.6/lib/python3.6/site-packages/pandas/plotting/_matplotlib/core.py", line 279, in generate
    self._compute_plot_data()
  File "/opt/biotools/miniconda3/envs/pinfish_3.6/lib/python3.6/site-packages/pandas/plotting/_matplotlib/core.py", line 414, in _compute_plot_data
    raise TypeError("no numeric data to plot")
TypeError: no numeric data to plot
```

**Comment by splaisan** [comment]
my very big error, I gave a gff instead of the stats file as input, please forgive me!
